version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_hot_reload
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true